version: '3.8'

services:

  revue-frontend:
    image: revue-frontend
    container_name: ${FRONTEND_HOST}
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - my_net

networks:
  my_net:
    external: false
    name: revue_my_network