version: '3.8'

services:

  media-server:
    image: bluenviron/mediamtx:latest
    container_name: ${MEDIA_SERVER_HOST}
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_PROTOCOLS=tcp
    restart: always
    networks:
      my-net:
        ipv4_address: 192.168.0.10

networks:
    my-net:
      name: revue-network
      external: true
