version: '3.8'

services:

  media-server:
    image: bluenviron/mediamtx:latest
    container_name: ${MEDIA_SERVER_HOST}
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_PROTOCOLS=tcp
    restart: always
    networks:
      my_network:
        ipv4_address: 172.20.0.50

#networks:
    #  my_net:
    #name: revue_my_network
    #external: true

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"