version: '3.8'

services:

  revue-alarm:
    image: revue-alarm
    container_name: ${ALARM_HOST}
    build:
      context: .
      dockerfile: ./alarm/Dockerfile
    restart: on-failure
    ports:
      - ${ALARM_PORT}:${ALARM_PORT}
    depends_on:
      - revue-alarm-db
      - ${KAFKA_HOST}
    networks:
      - my_net

  revue-alarm-db:
    image: mongo
    container_name: ${ALARM_DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ALARM_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ALARM_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${ALARM_DB_NAME}
    ports:
      - ${ALARM_DB_PORT}:27017
    volumes:
      - alarm_data:/data/db
      - ./alarm/db/alarm-init.js:/docker-entrypoint-initdb.d/alarm-init.js
    networks:
      - my_net

volumes:
  alarm_data:
    driver: local

networks:
  my_net:
    external: false
    name: revue_my_network