version: '3.8'

services:

  revue-notification:
    image: revue-alarm
    container_name: revue-alarm
    build:
      context: .
      dockerfile: ./notification/Dockerfile
    restart: on-failure
    ports:
      - ${ALARM_PORT}:${ALARM_PORT}
    depends_on:
      - revue-notification-db
      - ${KAFKA_HOST}

  revue-notification-db:
    image: mongo
    container_name: ${NOTIFICATION_DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOTIFICATION_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${NOTIFICATION_DB_NAME}
    ports:
      - ${NOTIFICATION_DB_PORT}:27017
    volumes:
      - notificationn_data:/data/db
      - ./notification/db/notification-init.js:/docker-entrypoint-initdb.d/notification-init.js

volumes:
  notification_data:
    driver: local
