version: '3.8'

services:

  revue-zookeeper:
    image: bitnami/zookeeper:latest
    container_name: revue-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  revue-kafka:
    image: bitnami/kafka:latest
    container_name: revue-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://revue-kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=revue-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#    volumes:
#      - kafka_data:/bitnami/kafka
#      - ~/kafka/data/zookeeper_data:/var/lib/zookeeper/data
#      - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
    depends_on:
      - revue-zookeeper

#volumes:
#  kafka_data:
#    driver: local
