name: Revue Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    # run on ubuntu, windows and macOS
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run build
        run: ./gradlew build --info
      - name: Run tests
        run: ./gradlew domain:test --info

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check format
        run: ./gradlew format --info
